#Start

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/AFAgarap/ecommerce-reviews-analysis/master/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [ ]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [ ]:
df=df.drop(['Unnamed: 0'], axis = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


#Removing empty text section

In [ ]:
df[df['Review Text'] == ""] =np.NAN

In [ ]:
df

Clothing ID   Age                                              Title  \
0            767.0  33.0                                                NaN   
1           1080.0  34.0                                                NaN   
2           1077.0  60.0                            Some major design flaws   
3           1049.0  50.0                                   My favorite buy!   
4            847.0  47.0                                   Flattering shirt   
...            ...   ...                                                ...   
23481       1104.0  34.0                     Great dress for many occasions   
23482        862.0  48.0                         Wish it was made of cotton   
23483       1104.0  31.0                              Cute, but see through   
23484       1084.0  28.0  Very cute dress, perfect for summer parties an...   
23485       1104.0  52.0                    Please make more like this one!   

                                             Review Text  Rating  \
0      Absolutely wonderful - silky and sexy and comf...     4.0   
1      Love this dress!  it's sooo pretty.  i happene...     5.0   
2      I had such high hopes for this dress and reall...     3.0   
3      I love, love, love this jumpsuit. it's fun, fl...     5.0   
4      This shirt is very flattering to all due to th...     5.0   
...                                                  ...     ...   
23481  I was very happy to snag this dress at such a ...     5.0   
23482  It reminds me of maternity clothes. soft, stre...     3.0   
23483  This fit well, but the top was very see throug...     3.0   
23484  I bought this dress for a wedding i have this ...     3.0   
23485  This dress in a lovely platinum is feminine an...     5.0   

       Recommended IND  Positive Feedback Count   Division Name  \
0                  1.0                      0.0       Initmates   
1                  1.0                      4.0         General   
2                  0.0                      0.0         General   
3                  1.0                      0.0  General Petite   
4                  1.0                      6.0         General   
...                ...                      ...             ...   
23481              1.0                      0.0  General Petite   
23482              1.0                      0.0  General Petite   
23483              0.0                      1.0  General Petite   
23484              1.0                      2.0         General   
23485              1.0                     22.0  General Petite   

      Department Name Class Name  
0            Intimate  Intimates  
1             Dresses    Dresses  
2             Dresses    Dresses  
3             Bottoms      Pants  
4                Tops    Blouses  
...               ...        ...  
23481         Dresses    Dresses  
23482            Tops      Knits  
23483         Dresses    Dresses  
23484         Dresses    Dresses  
23485         Dresses    Dresses  

[23486 rows x 10 columns]

In [ ]:
df['Review Text'].fillna("No Review",inplace =True)

#feature and label

In [ ]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [ ]:
x =df['Review Text']

In [ ]:
y=df['Rating']

In [ ]:
df['Review Text'].value_counts()

No Review                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 845
Perfect fit and i've gotten so many compliments. i buy all my suits from here now!                                                                                                                                                                                                                                                                                                                                                                                                                        

#Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test, y_train , y_test = train_test_split(x,y,train_size= 0.7 ,stratify = y,random_state = 12529) # random_state = any number (to fixed  the combination number of random combination )

# Get Feature Text Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text  import CountVectorizer

In [ ]:
cv = CountVectorizer(lowercase = True ,analyzer= 'word',ngram_range = (2,3),stop_words= 'english',max_features= 5000)

In [ ]:
x_train = cv.fit_transform(x_train)

In [ ]:
cv.get_feature_names_out()

array(['0p fit', '10 10', '10 12', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [ ]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_test = cv.fit_transform(x_test)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 fit', '10 got', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [ ]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get Model train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

#Get Model Prediction

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([5., 1., 5., ..., 3., 4., 4.])

#Get Probability of Each Predicted Class



In [ ]:
model.predict_proba(x_test)

array([[0.05195875, 0.08260154, 0.17570434, 0.22106802, 0.46866734],
       [0.36050981, 0.05009674, 0.11403525, 0.15638324, 0.31897497],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.05656578, 0.02108659, 0.48254844, 0.02343763, 0.41636156],
       [0.01070241, 0.00656414, 0.00939201, 0.92843325, 0.04490819],
       [0.03736085, 0.04541674, 0.05181356, 0.4371705 , 0.42823834]])

#Get Model Evaluation

#Model Accuracy 

In [ ]:
from sklearn.metrics import confusion_matrix ,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[  18   28   29   48  130]
 [  60   40   46  102  222]
 [ 101   86  100  185  389]
 [ 191  161  166  321  684]
 [ 421  401  355  788 1974]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.07      0.03       253
         2.0       0.06      0.09      0.07       470
         3.0       0.14      0.12      0.13       861
         4.0       0.22      0.21      0.22      1523
         5.0       0.58      0.50      0.54      3939

    accuracy                           0.35      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.35      0.37      7046



#Recategories Rating as poor (0) and Good (1)

In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [ ]:
df.replace({'Rating' : { 1:0 , 2:0,3:0,4:1,5:1}},inplace  = True)

In [ ]:
y = df['Rating']

In [ ]:
x = df['Review Text']

#Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test, y_train , y_test = train_test_split(x,y,train_size= 0.7 ,stratify = y , random_state = 12529) # random_state = any number (to fixed  the combination number of random combination )

# Get Feature Text Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text  import CountVectorizer

In [ ]:
cv = CountVectorizer(lowercase = True ,analyzer= 'word',ngram_range = (2,3),stop_words= 'english',max_features= 5000)

In [ ]:
x_train = cv.fit_transform(x_train)

In [ ]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 dress', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [ ]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x_test = cv.fit_transform(x_test)

In [ ]:
cv.get_feature_names_out()

array(['0p fit', '10 10', '10 12', ..., 'years come', 'yellow color',
       'yoga pants'], dtype=object)

In [ ]:
x_test.toarray()

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get Re-Model train

# Get Model train

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(x_train,y_train)

MultinomialNB()

#Get Model Prediction

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

#Model Accuracy 

In [ ]:
from sklearn.metrics import confusion_matrix ,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[ 326 1257]
 [1038 4425]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.24      0.21      0.22      1583
         1.0       0.78      0.81      0.79      5463

    accuracy                           0.67      7046
   macro avg       0.51      0.51      0.51      7046
weighted avg       0.66      0.67      0.67      7046

